//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnQLNCKH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailNotifi
    {
        public int Id { get; set; }
        public Nullable<int> IdNo { get; set; }
        public string DetalContent { get; set; }
    
        public virtual Notification Notification { get; set; }
    }
}
