//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DuAnQLNCKH.Models
{
    using System;
    using System.Collections.Generic;

    public partial class TopicOfLectureView
    {
        public TopicOfLecture topicOfLecture { get; set; }
        public Extension extension { get; set; }
        public PointTable pointTable { get; set; }
        public Information information { get; set; }
        public TopicOfStudent topicOfStudent { get; set; }
        public Type type { get; set; }
        public ProgressLe progressLe {get;set;}
        public Faculty faculty { get; set; }
     }
}
